version: "3"

services:
  containerdemo:
    image: "29c983f717e9"
    expose:
      - "5000"
  nginx:
    image: "bc7fdec94612"
    volumes:
      - G:\exploration\nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - containerdemo
    ports:
      - "4000:4000"