version: "3"

services:
  containerdemo:
    image: "containerdemo"
    expose:
      - "5000"
  nginx:
    image: "nginx"
    volumes:
      - G:\exploration\nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - containerdemo
    ports:
      - "4000:4000"
