@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
skinparam defaultFontName Segoe UI
skinparam RoundCorner 5

'Person(personAlias, "Label", "Optional Description")
'Person_Ext(label,"Person ext","optional")
'Container(containerAlias, "Label", "Technology", "Optional Description")
'System(systemAlias, "Label", "Optional Description")
'System_Ext(label,"Person ext","optional")
'Rel(personAlias, containerAlias, "Label", "Optional Technology")
Person(user,"Client Application","API client application","users")
System_Boundary(dicomstore,"Dicom Store") {
    Container(wado,"WADO"," retrieve metadata/pixeldata/bulkdata/par10")
    Container(qido,"QIDO","search for studies")
    Container(stow,"Stow","store studies")
}
System_Ext(objetstore, "Object Store")
System_Ext(cdr, "FHIR CDR")
Rel(user,dicomstore,"HTTP","Using DICOMweb API")
Rel(dicomstore,cdr,"HTTPS")
Rel(dicomstore,objetstore,"HTTPS")

@enduml